
export const GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER';
export const GET_RANDOM_NUMBER_SUCCESS = 'GET_RANDOM_NUMBER_SUCCESS';
export const GET_RANDOM_NUMBER_FALIURE = 'GET_RANDOM_NUMBER_FALIURE';
export const FETCH_AMENITIES = 'FETCH_AMENITIES';
export const FETCH_AMENITIES_SUCCESS = 'FETCH_AMENITIES_SUCCESS';
export const FETCH_AMENITIES_FAILURE = 'FETCH_AMENITIES_FAILURE';
export const FETCH_VENUE_OPTIONS = 'FETCH_VENUE_OPTIONS';
export const FETCH_VENUE_OPTIONS_SUCCESS = 'FETCH_VENUE_OPTIONS_SUCCESS';
export const FETCH_VENUE_OPTIONS_FAILURE = 'FETCH_VENUE_OPTIONS_FAILURE';